resources:
  - url: http://127.0.0.1:5000/thermostat-bar-card.js
    type: module
views:
  - cards:
      - type: custom:thermostat-bar-card
        name: Thermostat Bar Card Development
        entity: sun.sun
        test_gui: true
